#!/bin/sh

ENABLED=yes
PROCS=arpwatch
ARGS="-i br0"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -f /opt/lib/arpwatch/arp.dat ] || touch /opt/lib/arpwatch/arp.dat

. /opt/etc/init.d/rc.func
